#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSController
from mininet.node import CPULimitedHost, Host, Node
from mininet.node import OVSKernelSwitch, UserSwitch
from mininet.node import IVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf
from subprocess import call

def myNetwork():

    net = Mininet( topo=None,
                   build=False,
                   ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=RemoteController,
                      protocol='tcp',
                      port=6633,ip='127.0.0.1')

    info( '*** Add switches\n')
    ATH = net.addSwitch( 's1' )
    LIS = net.addSwitch( 's2' )
    LON = net.addSwitch( 's3' )
    BRU = net.addSwitch( 's4' )
    PAR = net.addSwitch( 's5' )
    DUB = net.addSwitch( 's6' )
    MAD = net.addSwitch( 's7' )
    GEN = net.addSwitch( 's8' )
    MIL = net.addSwitch( 's9' )
    SOF = net.addSwitch( 's10' )
    BUC = net.addSwitch( 's11' )
    VIE = net.addSwitch( 's12' )
    FRA = net.addSwitch( 's13' )
    COP = net.addSwitch( 's14' )
    TLN = net.addSwitch( 's15' )
    RIG = net.addSwitch( 's16' )
    KAU = net.addSwitch( 's17' )
    POZ = net.addSwitch( 's18' )
    PRA = net.addSwitch( 's19' )
    BRA = net.addSwitch( 's20' )
    ZAG = net.addSwitch( 's21' )
    LJU = net.addSwitch( 's22' )
    BUD = net.addSwitch( 's23' )
    MLT = net.addSwitch( 's24' )
    LUX = net.addSwitch( 's25' )
    MAR = net.addSwitch( 's26' )
    HAM = net.addSwitch( 's27' )
    AMS = net.addSwitch( 's28' )
    STO = net.addSwitch( 's29' )
    OSL = net.addSwitch( 's30' )
    HEL = net.addSwitch( 's31' )

    info( '*** Add hosts\n')
    ATH_host = net.addHost( 'h1' )
    LIS_host = net.addHost( 'h2' )
    LON_host = net.addHost( 'h3' )
    BRU_host = net.addHost( 'h4' )
    PAR_host = net.addHost( 'h5' )
    DUB_host = net.addHost( 'h6' )
    MAD_host = net.addHost( 'h7' )
    GEN_host = net.addHost( 'h8' )
    MIL_host = net.addHost( 'h9' )
    SOF_host = net.addHost( 'h10' )
    BUC_host = net.addHost( 'h11' )
    VIE_host = net.addHost( 'h12' )
    FRA_host = net.addHost( 'h13' )
    COP_host = net.addHost( 'h14' )
    TLN_host = net.addHost( 'h15' )
    RIG_host = net.addHost( 'h16' )
    KAU_host = net.addHost( 'h17' )
    POZ_host = net.addHost( 'h18' )
    PRA_host = net.addHost( 'h19' )
    BRA_host = net.addHost( 'h20' )
    ZAG_host = net.addHost( 'h21' )
    LJU_host = net.addHost( 'h22' )
    BUD_host = net.addHost( 'h23' )
    MLT_host = net.addHost( 'h24' )
    LUX_host = net.addHost( 'h25' )
    MAR_host = net.addHost( 'h26' )
    HAM_host = net.addHost( 'h27' )
    AMS_host = net.addHost( 'h28' )
    STO_host = net.addHost( 'h29' )
    OSL_host = net.addHost( 'h30' )
    HEL_host = net.addHost( 'h31' )

    info( '*** Add links\n')
    # add edges between switch and corresponding host
    net.addLink( ATH , ATH_host )
    net.addLink( LIS , LIS_host )
    net.addLink( LON , LON_host )
    net.addLink( BRU , BRU_host )
    net.addLink( PAR , PAR_host )
    net.addLink( DUB , DUB_host )
    net.addLink( MAD , MAD_host )
    net.addLink( GEN , GEN_host )
    net.addLink( MIL , MIL_host )
    net.addLink( SOF , SOF_host )
    net.addLink( BUC , BUC_host )
    net.addLink( VIE , VIE_host )
    net.addLink( FRA , FRA_host )
    net.addLink( COP , COP_host )
    net.addLink( TLN , TLN_host )
    net.addLink( RIG , RIG_host )
    net.addLink( KAU , KAU_host )
    net.addLink( POZ , POZ_host )
    net.addLink( PRA , PRA_host )
    net.addLink( BRA , BRA_host )
    net.addLink( ZAG , ZAG_host )
    net.addLink( LJU , LJU_host )
    net.addLink( BUD , BUD_host )
    net.addLink( MLT , MLT_host )
    net.addLink( LUX , LUX_host )
    net.addLink( MAR , MAR_host )
    net.addLink( HAM , HAM_host )
    net.addLink( AMS , AMS_host )
    net.addLink( STO , STO_host )
    net.addLink( OSL , OSL_host )
    net.addLink( HEL , HEL_host )

# add edges between switches
    net.addLink( ATH , MIL )
    net.addLink( MIL , ATH )
    net.addLink( MIL , VIE )
    net.addLink( MIL , MAR )
    net.addLink( MIL , GEN )
    net.addLink( GEN , MIL )
    net.addLink( MIL , MLT )
    net.addLink( GEN , FRA )
    net.addLink( FRA , GEN )
    net.addLink( GEN , PAR )
    net.addLink( PAR , GEN )
    net.addLink( GEN , PAR )
    net.addLink( FRA , POZ )
    net.addLink( GEN , MAR )
    net.addLink( MAR , MAD )
    net.addLink( MAD , PAR )
    net.addLink( MAD , LIS )
    net.addLink( LIS , LON )
    net.addLink( LON , LIS )
    net.addLink( LON , PAR )
    net.addLink( LON , DUB )
    net.addLink( DUB , LON )
    net.addLink( LON , BRU )
    net.addLink( BRU , AMS )
    net.addLink( AMS , LUX )
    net.addLink( LUX , FRA )
    net.addLink( AMS , HAM )
    net.addLink( HAM , FRA )
    net.addLink( HAM , COP )
    net.addLink( COP , AMS )
    net.addLink( FRA , POZ )
    net.addLink( FRA , PRA )
    net.addLink( FRA , BUD )
    net.addLink( FRA , VIE )
    net.addLink( POZ , PRA )
    net.addLink( POZ , KAU )
    net.addLink( KAU , RIG )
    net.addLink( ZAG , VIE )
    net.addLink( ZAG , BUD )
    net.addLink( BUD , PRA )
    net.addLink( BUD , BRA )
    net.addLink( BUD , BUC )
    net.addLink( BUD , SOF )
    net.addLink( BUD , LJU )
    net.addLink( BUC , SOF )
    net.addLink( BUC , VIE )
    net.addLink( VIE , BRA )
    net.addLink( RIG , TLN )
    net.addLink( TLN , HAM )
    net.addLink( OSL , STO )
    net.addLink( STO , HEL )
    net.addLink( STO , COP )
    net.addLink( OSL , COP )
    net.addLink( TLN , HEL )
    
    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches\n')
    for switch in net.switches:
        net.get(str(switch)).start([c0])


    info( '*** Post configure switches and hosts\n')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

